name: Build

on: [ push ]

jobs:
  run-test:
    uses: ./.github/workflows/_test.yml

  build:
    runs-on: ubuntu-latest
    needs: run-test

    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/go-upstream-auth-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-upstream-auth-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/go-upstream-auth-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]

    permissions:
      contents: write

    steps:
      - name: Download artifact ${{ matrix.goos }}-${{ matrix.goarch }}
        uses: actions/download-artifact@v4
        with:
          name: go-upstream-auth-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/go-upstream-auth-${{ matrix.goos }}-${{ matrix.goarch }}